const personaggi = [
  {
    nome: "Eren Jaeger",
    eta: 15,
    divisione: "Corpo di Ricerca",
    grado: "Recluta",
    specializzazione: "Combattimento corpo a corpo",
    titano: "Attacco",
    statistiche: {
      forza: 7,
      agilita: 8,
      intelligenza: 5,
      coraggio: 10,
      carisma: 4,
    },
    abilita: ["Furia del titano", "Manovra 3D avanzata"],
    background:
      "Ha giurato di sterminare tutti i titani dopo la distruzione di Shiganshina.",
  },
  {
    nome: "Kael Riven",
    eta: 22,
    divisione: "Guarnigione",
    grado: "Caporale",
    specializzazione: "Tattiche difensive",
    titano: null,
    statistiche: {
      forza: 6,
      agilita: 5,
      intelligenza: 8,
      coraggio: 6,
      carisma: 7,
    },
    abilita: ["Costruzione di barricate", "Coordinamento truppe"],
    background:
      "Veterano di Trost, specializzato in strategie di contenimento.",
  },
  {
    nome: "Lira Velkan",
    eta: 19,
    divisione: "Corpo di Ricerca",
    grado: "Recluta",
    specializzazione: "Manovra 3D",
    titano: null,
    statistiche: {
      forza: 5,
      agilita: 9,
      intelligenza: 6,
      coraggio: 8,
      carisma: 4,
    },
    abilita: ["Scatto aereo", "Attacco circolare"],
    background: "Agile e silenziosa, preferisce l’azione alla pianificazione.",
  },
  {
    nome: "Damon Kreiss",
    eta: 27,
    divisione: "Brigata Speciale",
    grado: "Capitano",
    specializzazione: "Interrogatori e sorveglianza",
    titano: null,
    statistiche: {
      forza: 6,
      agilita: 6,
      intelligenza: 9,
      coraggio: 5,
      carisma: 7,
    },
    abilita: ["Analisi comportamentale", "Manipolazione"],
    background:
      "Addestrato per proteggere il Re, ha una morale ambigua e un passato oscuro.",
  },
  {
    nome: "Mira Ral",
    eta: 18,
    divisione: "Corpo di Ricerca",
    grado: "Recluta",
    specializzazione: "Supporto medico",
    titano: null,
    statistiche: {
      forza: 4,
      agilita: 6,
      intelligenza: 9,
      coraggio: 7,
      carisma: 6,
    },
    abilita: ["Pronto soccorso", "Preparazione pozioni"],
    background:
      "Orfana cresciuta da un chirurgo, crede che salvare vite sia più importante che toglierle.",
  },
  {
    nome: "Rogan Brandt",
    eta: 30,
    divisione: "Guarnigione",
    grado: "Comandante",
    specializzazione: "Armi pesanti",
    titano: null,
    statistiche: {
      forza: 9,
      agilita: 4,
      intelligenza: 6,
      coraggio: 9,
      carisma: 6,
    },
    abilita: ["Uso cannoni anti-Titano", "Comando sul campo"],
    background: "Ha guidato la difesa di Utopia per tre giorni senza rinforzi.",
  },
  {
    nome: "Seren Aven",
    eta: 20,
    divisione: "Cadetti",
    grado: "Recluta",
    specializzazione: "Ricognizione",
    titano: null,
    statistiche: {
      forza: 5,
      agilita: 8,
      intelligenza: 7,
      coraggio: 6,
      carisma: 5,
    },
    abilita: ["Mimetizzazione", "Tracciamento"],
    background:
      "Nata fuori le mura, sa sopravvivere meglio dei suoi istruttori.",
  },
  {
    nome: "Thorn Heller",
    eta: 24,
    divisione: "Brigata Speciale",
    grado: "Caporale",
    specializzazione: "Difesa ravvicinata",
    titano: null,
    statistiche: {
      forza: 8,
      agilita: 7,
      intelligenza: 4,
      coraggio: 9,
      carisma: 3,
    },
    abilita: ["Scudo rotante", "Urlo da battaglia"],
    background:
      "Considerato un muro umano, è temuto e rispettato per la sua forza bruta.",
  },
  {
    nome: "Elya Kraus",
    eta: 23,
    divisione: "Corpo di Ricerca",
    grado: "Capitano",
    specializzazione: "Strategia",
    titano: null,
    statistiche: {
      forza: 4,
      agilita: 5,
      intelligenza: 10,
      coraggio: 8,
      carisma: 6,
    },
    abilita: ["Pianificazione imboscate", "Comando remoto"],
    background: "Allieva di Erwin Smith, ha ereditato il suo acume tattico.",
  },
  {
    nome: "Garrik Stone",
    eta: 29,
    divisione: "Guarnigione",
    grado: "Capitano",
    specializzazione: "Difesa delle mura",
    titano: null,
    statistiche: {
      forza: 7,
      agilita: 4,
      intelligenza: 6,
      coraggio: 8,
      carisma: 7,
    },
    abilita: ["Comando difensivo", "Riparazione strutture"],
    background:
      "Sopravvissuto a due cadute delle mura, ha giurato di non lasciare che accada una terza volta.",
  },
];
